# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phloem
email: wil.pearson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Phloem is a project to make a protocol for the mangement of electricity in small scale applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: eb3c90
github_username:  eb4890

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman